//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderDetailsTable
    {
        public int RiderID { get; set; }
        public string RiderCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Mobile { get; set; }
        public string Password { get; set; }
        public string CurrentLocation { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public int Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
