//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideDetailsTable
    {
        public int RideID { get; set; }
        public int UserID { get; set; }
        public int DriverID { get; set; }
        public string PickupAddress { get; set; }
        public string DropAddress { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<System.TimeSpan> PickupTime { get; set; }
        public string Distance { get; set; }
        public string Duration { get; set; }
        public Nullable<int> RideStatus { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<int> PayDriver { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string Amount { get; set; }
    }
}
