//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingVehicleImageTable
    {
        public int SVITID { get; set; }
        public Nullable<int> SellingID { get; set; }
        public string ImageUrl { get; set; }
    }
}
