//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiServiceEntities : DbContext
    {
        public TaxiServiceEntities()
            : base("name=TaxiServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetailsTable> AdminDetailsTables { get; set; }
        public virtual DbSet<DriverDetailsTable> DriverDetailsTables { get; set; }
        public virtual DbSet<HireState> HireStates { get; set; }
        public virtual DbSet<LocationsTable> LocationsTables { get; set; }
        public virtual DbSet<PaymentModeTable> PaymentModeTables { get; set; }
        public virtual DbSet<PaymentStatusTable> PaymentStatusTables { get; set; }
        public virtual DbSet<RideDetailsTable> RideDetailsTables { get; set; }
        public virtual DbSet<RiderDetailsTable> RiderDetailsTables { get; set; }
        public virtual DbSet<RideStatusTable> RideStatusTables { get; set; }
        public virtual DbSet<SellingVehicleDetail> SellingVehicleDetails { get; set; }
        public virtual DbSet<SellingVehicleImageTable> SellingVehicleImageTables { get; set; }
        public virtual DbSet<TripDetaisTable> TripDetaisTables { get; set; }
        public virtual DbSet<TripsTable> TripsTables { get; set; }
        public virtual DbSet<UserLoginDetail> UserLoginDetails { get; set; }
        public virtual DbSet<UserStatusTable> UserStatusTables { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
    }
}
