//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripsTable
    {
        public int TripID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public int TripDetailsTableID { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<System.TimeSpan> PickupTime { get; set; }
        public Nullable<int> TripStatus { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<int> PayDriver { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string Amount { get; set; }
        public string RequestedBy { get; set; }
        public string RequesterContact { get; set; }
        public string TripDetail { get; set; }
        public string DriverName { get; set; }
        public string DriverContact { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public Nullable<int> TripDays { get; set; }
    }
}
