//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripDetaisTable
    {
        public int TripID { get; set; }
        public string TripFrom { get; set; }
        public string TripTo { get; set; }
        public int VanPerDay { get; set; }
        public int BusPerDay { get; set; }
        public Nullable<int> VanPerKm { get; set; }
        public Nullable<int> BusPerKm { get; set; }
        public Nullable<int> VanPerHr { get; set; }
        public Nullable<int> BusPerHr { get; set; }
        public string DistanceKm { get; set; }
        public string DurationHr { get; set; }
        public int CarPerDay { get; set; }
        public Nullable<int> CarPerKm { get; set; }
        public Nullable<int> CarPerHr { get; set; }
        public string ImageUrl { get; set; }
    }
}
