//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginDetail
    {
        public int UserLoginID { get; set; }
        public int UserTableID { get; set; }
        public string UserLoginEmail { get; set; }
        public int UserLoginMobile { get; set; }
        public string UserLoginPassword { get; set; }
        public int UserType { get; set; }
    }
}
